services:
  fastapi:
    build:
      context: .
      no_cache: true
    volumes:
      - ./qr_codes:/myapp/qr_codes
      - .:/myapp/
    environment:
      - QR_CODE_DIR=/myapp/qr_codes
      - FILL_COLOR=red
      - BACK_COLOR=white
    networks:
      - app-network
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./qr_codes:/var/www/qr_codes
    depends_on:
      - fastapi
    networks:
      - app-network
networks:
  app-network:
    driver: bridge